logging.level:
  org.menagerie.stnotifier: 'DEBUG'
  org.apache.http.wire: 'WARN'
  httpclient.wire.header: 'WARN'
  httpclient.wire.content: 'WARN'
  org.apache: 'WARN'
  org.apache.commons.httpclient: 'WARN'
twilio:
  account:
    sid: ACcfac9b8e682bc0574fdf46d2abc5997b
    authToken: 065cc25e253e8ba0efb358afdddae73b
server:
  port: 8085
spring:
  data:
    mongodb:
      host: 1.tcp.ngrok.io
      port: 29180
  cloud:
    stream:
      bindings:
        input:
          destination: stnotifier
          binder: rabbit1
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 1.tcp.ngrok.io
                port: 29179