logging.level:
  org.menagerie.stnotifier: 'DEBUG'
  org.apache.http.wire: 'WARN'
  httpclient.wire.header: 'WARN'
  httpclient.wire.content: 'WARN'
  org.apache: 'WARN'
  org.apache.commons.httpclient: 'WARN'
twilio:
  account:
    sid: ACcfac9b8e682bc0574fdf46d2abc5997b
    authKey: SK587ef218d310715545098c10e8d885d8
    authToken: 8DXrPQpwA4HslnNix1ct7WFUKbNx3HVt
menagerie:
  video:
    camera: Nikon-D7100
server:
  port: 8085
spring:
  profiles:
    active: default,gpio,camera
  data:
    mongodb:
      host: 1.tcp.ngrok.io
      port: 29180
  cloud:
    stream:
      bindings:
        input:
          consumer:
            maxAttempts: 1
          destination: stnotifier
          binder: rabbit1
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 1.tcp.ngrok.io
                port: 29179