java:
  awt:
    headless: false
logging:
  level:
    org.springframework.data.mongodb: WARN
    org.menagerie.stnotifier: DEBUG
    org.springframework.boot: WARN
menagerie:
  stnotifier:
    wait:
      betweenMessages: 60000
      start: 5000
      end: 5000
      space: 950
    onTime: 1200
    offTime: 200
  i2c:
    bus: 1
    ht16k33:
      address: 0x70
spring:
  profiles:
    active: default,gpio
  cloud:
    stream:
      bindings:
        output:
          destination: stnotifier
          binder: rabbit1
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 1.tcp.ngrok.io
                port: 29179