java:
  awt:
    headless: false
logging:
  level:
    org.springframework.data.mongodb: DEBUG
    org.menagerie.stnotifier: DEBUG
    org.springframework.boot: DEBUG
menagerie:
  stnotifier:
    wait:
      betweenMessages: 60000
      start: 5000
      end: 5000
      space: 650
    onTime: 600
    offTime: 50
  i2c:
    bus: 1
    ht16k33:
      address: 0x70
spring:
  cloud:
    stream:
      bindings:
        output:
          destination: stnotifier